CREATE DATABASE Test_SWP391_Group3;
GO
USE Test_SWP391_Group3;

CREATE TABLE [Users] (
    userID INT PRIMARY KEY IDENTITY(1,1),
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
);